// Generated by scripts/build-assets.mjs. Do not edit.
export const ASSETS = {
  "fonts/figtree-latin.woff2": "/assets/figtree-latin.8330490a01.woff2",
  "fonts/figtree-latin-ext.woff2": "/assets/figtree-latin-ext.f153aa07c1.woff2",
  "band.mp4": "/video/band.282e918b13.mp4",
  "poster.webp": "/assets/poster.f972ce8a50.webp",
  "mark.svg": "/assets/mark.a16ec2317e.svg",
  "boot.js": "/assets/boot.2d7f7354b4.js",
  "roamid.js": "/assets/roamid.3b9a1bd2bc.js",
  "roamid.css": "/assets/roamid.6ef9ba9c39.css"
};
// Byte sizes of the files served with ranges (the assets binding streams without Content-Length).
export const SIZES = {
  "/video/band.282e918b13.mp4": 13717501
};
