#!/usr/bin/env node
// Content-hashed static assets: assets/ -> public/assets/<name>.<hash>.<ext>,
// and src/ui/manifest.js (logical name -> URL path) for the Worker.
//   node scripts/build-assets.mjs           build public/ and the manifest
//   node scripts/build-assets.mjs --check   fail when the manifest is stale
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SERVED = ["mark.svg", "lab-logo.webp", "lab-logo.png", "roamid.js", "roamid.css"];
const check = process.argv.includes("--check");

const hashed = (name, buf) => {
  const h = createHash("sha256").update(buf).digest("hex").slice(0, 10);
  return `/${name.endsWith(".mp4") ? "video" : "assets"}/${basename(name, extname(name))}.${h}${extname(name)}`;
};
const map = {};
const outputs = [];
for (const name of SERVED) {
  let buf = readFileSync(join(root, "assets", name));
  if (name.endsWith(".css")) buf = Buffer.from(buf.toString("utf8").replace(/asset:([\w./-]+)/g, (_, n) => { if (!map[n]) throw new Error(`${name}: unknown asset ${n}`); return map[n]; }));
  map[name] = hashed(name, buf);
  outputs.push([map[name], buf]);
}
const sizes = Object.fromEntries(outputs.filter(([p]) => p.endsWith(".mp4")).map(([p, buf]) => [p, buf.length]));
const manifest = `// Generated by scripts/build-assets.mjs. Do not edit.\nexport const ASSETS = ${JSON.stringify(map, null, 2)};\n// Byte sizes of the files served with ranges (the assets binding streams without Content-Length).\nexport const SIZES = ${JSON.stringify(sizes, null, 2)};\n`;
const mpath = join(root, "src/ui/manifest.js");
if (check) {
  const cur = existsSync(mpath) ? readFileSync(mpath, "utf8") : "";
  if (cur !== manifest) { console.error("src/ui/manifest.js is stale: run node scripts/build-assets.mjs"); process.exit(1); }
  console.log("manifest up to date");
  process.exit(0);
}
rmSync(join(root, "public"), { recursive: true, force: true });
mkdirSync(join(root, "public/assets"), { recursive: true });
// Video is stored under /media/ and served at /video/ by the Worker, which
// adds byte ranges (src/lib/range.js); the assets binding has no Range support.
mkdirSync(join(root, "public/media"), { recursive: true });
for (const [p, buf] of outputs) writeFileSync(join(root, "public", p.endsWith(".mp4") ? p.replace("/video/", "/media/") : p), buf);
writeFileSync(join(root, "public/_headers"), ["/assets/*", "/media/*"].map((p) => `${p}\n  Cache-Control: public, max-age=31536000, immutable\n  X-Content-Type-Options: nosniff\n  Access-Control-Allow-Origin: *\n`).join(""));
writeFileSync(mpath, manifest);
console.log(Object.entries(map).map(([k, v]) => `${k} -> ${v}`).join("\n"));
