#!/usr/bin/env node
// docs/*.md and docs/zh-CN/*.md -> src/ui/docs-content.js, which the Worker
// serves at /docs/<slug> and /zh/docs/<slug>. The Markdown files in the
// repository stay the source; this module is regenerated by
// scripts/build-assets.mjs on every deploy (and can be run alone).
//   node scripts/build-docs.mjs
// "updated" is the date of the last commit that touched the file.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, dirname, posix } from "node:path";
import { fileURLToPath } from "node:url";
import { render } from "./markdown.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const REPO = "https://github.com/FadianRoam/roamid";
// Reading order on /docs; files not listed here follow in name order.
const ORDER = ["rp-integration", "idp-requirements", "registry", "policy", "errors", "conformance", "operations"];

const gitDate = (file) => {
  try { return execFileSync("git", ["log", "-1", "--format=%cs", "--", file], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim() || null; } catch { return null; }
};

export function buildDocs() {
  const en = readdirSync(join(root, "docs")).filter((f) => /^[a-z0-9-]+\.md$/.test(f)).map((f) => f.slice(0, -3));
  const slugs = [...ORDER.filter((s) => en.includes(s)), ...en.filter((s) => !ORDER.includes(s)).sort()];
  const has = (lang, slug) => existsSync(join(root, lang === "zh" ? "docs/zh-CN" : "docs", `${slug}.md`));
  const one = (lang, slug) => {
    const file = lang === "zh" ? `docs/zh-CN/${slug}.md` : `docs/${slug}.md`;
    const link = (href) => {
      if (/^[a-z][a-z0-9+.-]*:/i.test(href) || href.startsWith("#")) return href;
      const [p, hash] = href.split("#");
      const h = hash ? `#${hash}` : "";
      const repoPath = posix.normalize(p.startsWith("/") ? p.slice(1) : posix.join(posix.dirname(file), p));
      let m = /^docs\/([a-z0-9-]+)\.md$/.exec(repoPath);
      if (m && has("en", m[1])) return `/docs/${m[1]}${h}`;
      m = /^docs\/zh-CN\/([a-z0-9-]+)\.md$/.exec(repoPath);
      if (m && has("zh", m[1])) return `/zh/docs/${m[1]}${h}`;
      const dir = repoPath.endsWith("/") || !/\.[a-z0-9]+$/i.test(repoPath);
      return `${REPO}/${dir ? "tree" : "blob"}/main/${repoPath.replace(/\/$/, "")}${h}`;
    };
    const drop = (line) => /^\[(English|简体中文|中文)\]\([^)]*\)$/.test(line);
    const r = render(readFileSync(join(root, file), "utf8"), { link, drop });
    return { title: r.title || slug, summary: r.description, html: r.html, updated: gitDate(file), source: `${REPO}/blob/main/${file}` };
  };
  return slugs.map((slug) => ({ slug, en: one("en", slug), zh: has("zh", slug) ? one("zh", slug) : null }));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const docs = buildDocs();
  const out = `// Generated by scripts/build-docs.mjs from docs/*.md. Do not edit.\nexport const DOCS = ${JSON.stringify(docs, null, 1)};\n`;
  writeFileSync(join(root, "src/ui/docs-content.js"), out);
  console.log(docs.map((d) => `${d.slug}${d.zh ? " (en, zh)" : " (en)"} ${d.en.updated || "-"}`).join("\n"));
}
